### ISSUE TITLE
 Test-token folder sls deploy not finding authorizer arn

### ISSUE THREAD

**Issue by QuantumInformation** [laardee/serverless-authentication-boilerplate#38]
I am trying to sun sls deploy on the test-token folder but am getting

`     - Function not found: arn:aws:lambda:us-east-1:180971085012:function:uz4g3f3m8i.`

previously I  Installed the authentication sls and got
```endpoints:
  GET - https://uz4g3f3m8i.execute-api.us-east-1.amazonaws.com/dev/authentication/signin/{provider}
  GET - https://uz4g3f3m8i.execute-api.us-east-1.amazonaws.com/dev/authentication/callback/{provider}
  GET - https://uz4g3f3m8i.execute-api.us-east-1.amazonaws.com/dev/authentication/refresh/{refresh_token}
```

Any ideas what else I can try?

**Comment by laardee** [comment]
Hi @QuantumInformation, is that the authorizer arn? The last part should be something like `serverless-authentication-dev-authorize`, where 
`serverless-authentication` is the service name you have defined in authentication service, 
`dev` is the stage and 
`authorize` is the name of the authorize function.
`arn:aws:lambda:us-east-1:180971085012:function:serverless-authentication-dev-authorize`

The function name should also be displayed after those endpoint when you deploy the authentication service or run `sls info` in authentication service root directory.

**Comment by QuantumInformation** [comment]
What I tried was:
![image](https://cloud.githubusercontent.com/assets/216566/23797956/3a962446-059a-11e7-9b60-1ca161cfcb64.png)

**Comment by laardee** [comment]
ok, can you run the `sls info` in the authentication directory? It should display the name of the authorizer function. 

The output something like this:
```
Service Information
service: dev-auth
stage: dev
region: eu-central-1
api keys:
  None
endpoints:
  GET - https://**********.execute-api.eu-central-1.amazonaws.com/dev/authentication/signin/{provider}
  GET - https://**********.execute-api.eu-central-1.amazonaws.com/dev/authentication/callback/{provider}
  GET - https://**********.execute-api.eu-central-1.amazonaws.com/dev/authentication/refresh/{refresh_token}
functions:
  signin: dev-auth-dev-signin
  callback: dev-auth-dev-callback
  refresh: dev-auth-dev-refresh
  authorize: dev-auth-dev-authorize
  schema: dev-auth-dev-schema
MacBook-Pro:authentication eetut$ 
```

**Comment by QuantumInformation** [comment]
Cool thanks

**Comment by QuantumInformation** [comment]
Why did you decide to split the serverless.yml into two?
