### ISSUE TITLE
Serverless project install with name parameter

### ISSUE THREAD

**Issue by laardee** [laardee/serverless-authentication-boilerplate#4]
Project name variable doesn't work when installing boilerplate, check if it is serverless issue

**Comment by ac360** [comment]
@laardee In V0.5 we stopped allowing the name to be changed in ProjectInit/Install.  It created too much confusion amongst teams who are collaborating on the same project.  Would love your input here.  Fantastic work by the way :)

**Comment by laardee** [comment]
Thanks @ac360, I talked about this with my colleague and he opened an issue to the Serverless project https://github.com/serverless/serverless/issues/923. I'll close this one and let's continue the conversation in that issue.
