### ISSUE TITLE
Broken link: custom provider on the demo page

### ISSUE THREAD

**Issue by microamp** [laardee/serverless-authentication-boilerplate#44]
CUSTOM-GOOGLE on http://laardee.github.io/serverless-authentication-gh-pages redirects to

> Error: redirect_uri_mismatch

with 400.

**Comment by laardee** [comment]
@microamp, thanks, I'll check that out.

**Comment by laardee** [comment]
Fixed, I forgot to update custom google callback URL to google app last time I deployed the service from scratch.

**Comment by microamp** [comment]
@laardee Thanks for fixing it so quickly. Seems all working now! 👍
