### ISSUE TITLE
How to redirect to originating page?

### ISSUE THREAD

**Issue by rentrop** [laardee/serverless-authentication-boilerplate#7]
Is there a way to redirect the user to his/her current position?

E.g. The user is on /cars. After he logs in i want him to be end up on /cars again.
If he is on /watches i want him to be redirected to /watches.

As far as i understand 
```
"redirectClientURI": "http://url-to-frontend-webapp/"
```
determins the redirect URI. How can i make something like `"redirectClientURI": "origin"` work?

**Comment by laardee** [comment]
Maybe you could map header referer and use that as a redirectClientURI. 

Here is a small example: 
https://jsfiddle.net/9t9kysaz/

In the Api Gateway I've mapped origin and referer (requestTemplates in s-function.json) 

```
{
    "origin": "$input.params().header.origin",
    "referer": "$input.params().header.referer"
}
```

And then I have simple Lambda function that returns mapped data
```
exports.handler = function(event, context) {
    context.succeed(event);
};
```

**Comment by rentrop** [comment]
Perfect. Thank you i will work to make it happend
