### ISSUE TITLE
Developer Authenticated Identities

### ISSUE THREAD

**Issue by mikedizon** [laardee/serverless-authentication-boilerplate#9]
Are there plans to support Developer Authenticated Identities?

http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

LambdaAuth does this, but it would be nice to have it as a serverless plugin

https://github.com/danilop/LambdAuth

**Comment by laardee** [comment]
This is a good feature to include to the boilerplate, at least as an example implementation. I'll look into this.

**Comment by laardee** [comment]
I'll close this one and let's continue the conversation in this issue https://github.com/laardee/serverless-authentication-boilerplate/issues/30
